apiVersion: apps/v1
kind: Deployment
metadata:
  name: liferay
  labels:
    app: liferay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liferay
  template:
    metadata:
      labels:
        app: liferay
    spec:
      containers:
        - name: liferay
          image: liferay/portal:7.4.3.79-ga79
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "2048Mi"
              cpu: "1000m"
            requests:
              memory: "1024Mi"
              cpu: "500m"
