apiVersion: v1
kind: Service
metadata:
  name: liferay
  labels:
    app.kubernetes.io/instance: liferay-basic
spec:
  type: NodePort
  selector:
    app: liferay
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30036  # ✅ Pick something between 30000-32767

